/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    sessions: Session;
    providers: Provider;
    categories: Category;
    tags: Tag;
    tools: Tool;
    campaigns: Campaign;
    'redirect-links': RedirectLink;
    'click-events': ClickEvent;
    'geo-routes': GeoRoute;
    'search-queries': SearchQuery;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    providers: ProvidersSelect<false> | ProvidersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    tools: ToolsSelect<false> | ToolsSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    'redirect-links': RedirectLinksSelect<false> | RedirectLinksSelect<true>;
    'click-events': ClickEventsSelect<false> | ClickEventsSelect<true>;
    'geo-routes': GeoRoutesSelect<false> | GeoRoutesSelect<true>;
    'search-queries': SearchQueriesSelect<false> | SearchQueriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  user: number | User;
  token: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Read-only mirror of the Prisma Provider catalog (Payload PoC). Prisma remains authoritative.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers".
 */
export interface Provider {
  id: number;
  /**
   * Original Prisma Provider.id (cuid).
   */
  legacyPrismaId: string;
  name: string;
  slug: string;
  description?: string | null;
  websiteUrl?: string | null;
  logo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mirror of the Prisma Category catalog. Prisma remains authoritative.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Original Prisma Category.id (cuid).
   */
  legacyPrismaId: string;
  name: string;
  slug: string;
  description?: string | null;
  icon?: string | null;
  /**
   * Matches Prisma Category.sortOrder (Int, default 0).
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mirror of the Prisma Tag catalog. Prisma remains authoritative.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Original Prisma Tag.id (cuid).
   */
  legacyPrismaId: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mirror of the Prisma Tool catalog. Prisma remains authoritative.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools".
 */
export interface Tool {
  id: number;
  /**
   * Original Prisma Tool.id (cuid).
   */
  legacyPrismaId: string;
  name: string;
  slug: string;
  description: string;
  websiteUrl: string;
  logo?: string | null;
  affiliateUrl?: string | null;
  /**
   * Prisma enum: free, freemium, paid, contact.
   */
  pricingType?: string | null;
  /**
   * Matches Prisma Tool.rating (Float, default 0).
   */
  rating?: number | null;
  isFeatured?: boolean | null;
  isPublished?: boolean | null;
  isSponsored?: boolean | null;
  /**
   * Legacy comma-separated tag string. Preserved for backward compatibility.
   */
  tags?: string | null;
  hostingGuide?: string | null;
  /**
   * Application-level enum: TOOL, MODEL, AGENT, API, RESOURCE.
   */
  entityType?: string | null;
  /**
   * VERIFIED, NEEDS_REVIEW, UNVERIFIED, INACTIVE.
   */
  verificationStatus?: string | null;
  lastVerifiedAt?: string | null;
  sourceUrl?: string | null;
  metadata?: string | null;
  documentationUrl?: string | null;
  pricingUrl?: string | null;
  /**
   * Resolves through Category.legacyPrismaId (no cross-database FK).
   */
  category: number | Category;
  /**
   * Resolves through Provider.legacyPrismaId. Null if tool has no provider.
   */
  provider?: (number | null) | Provider;
  /**
   * Recreates Prisma ToolTag join table. Resolves through Tag.legacyPrismaId.
   */
  structuredTags?: (number | Tag)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: number;
  name: string;
  description?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirect-links".
 */
export interface RedirectLink {
  id: number;
  slug: string;
  name: string;
  destination: string;
  tool?: (number | null) | Tool;
  campaign?: (number | null) | Campaign;
  isActive?: boolean | null;
  clickCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "click-events".
 */
export interface ClickEvent {
  id: number;
  /**
   * Original primary key from the legacy Prisma database.
   */
  legacyPrismaId?: string | null;
  link: number | RedirectLink;
  timestamp: string;
  referrer?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmContent?: string | null;
  utmTerm?: string | null;
  country?: string | null;
  deviceType?: string | null;
  browser?: string | null;
  operatingSystem?: string | null;
  isSuspicious?: boolean | null;
  trafficType?: ('human' | 'suspicious' | 'bot') | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geo-routes".
 */
export interface GeoRoute {
  id: number;
  link: number | RedirectLink;
  country: string;
  destination: string;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-queries".
 */
export interface SearchQuery {
  id: number;
  query: string;
  normalized: string;
  resultCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'providers';
        value: number | Provider;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'tools';
        value: number | Tool;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: number | Campaign;
      } | null)
    | ({
        relationTo: 'redirect-links';
        value: number | RedirectLink;
      } | null)
    | ({
        relationTo: 'click-events';
        value: number | ClickEvent;
      } | null)
    | ({
        relationTo: 'geo-routes';
        value: number | GeoRoute;
      } | null)
    | ({
        relationTo: 'search-queries';
        value: number | SearchQuery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  user?: T;
  token?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers_select".
 */
export interface ProvidersSelect<T extends boolean = true> {
  legacyPrismaId?: T;
  name?: T;
  slug?: T;
  description?: T;
  websiteUrl?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  legacyPrismaId?: T;
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  legacyPrismaId?: T;
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools_select".
 */
export interface ToolsSelect<T extends boolean = true> {
  legacyPrismaId?: T;
  name?: T;
  slug?: T;
  description?: T;
  websiteUrl?: T;
  logo?: T;
  affiliateUrl?: T;
  pricingType?: T;
  rating?: T;
  isFeatured?: T;
  isPublished?: T;
  isSponsored?: T;
  tags?: T;
  hostingGuide?: T;
  entityType?: T;
  verificationStatus?: T;
  lastVerifiedAt?: T;
  sourceUrl?: T;
  metadata?: T;
  documentationUrl?: T;
  pricingUrl?: T;
  category?: T;
  provider?: T;
  structuredTags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirect-links_select".
 */
export interface RedirectLinksSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  destination?: T;
  tool?: T;
  campaign?: T;
  isActive?: T;
  clickCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "click-events_select".
 */
export interface ClickEventsSelect<T extends boolean = true> {
  legacyPrismaId?: T;
  link?: T;
  timestamp?: T;
  referrer?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  utmContent?: T;
  utmTerm?: T;
  country?: T;
  deviceType?: T;
  browser?: T;
  operatingSystem?: T;
  isSuspicious?: T;
  trafficType?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geo-routes_select".
 */
export interface GeoRoutesSelect<T extends boolean = true> {
  link?: T;
  country?: T;
  destination?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-queries_select".
 */
export interface SearchQueriesSelect<T extends boolean = true> {
  query?: T;
  normalized?: T;
  resultCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}